### ISSUE TITLE
About Test Part

### ISSUE THREAD

**Issue by Arginonn** [GuoweiXu368/SLD-HMP#1]
Hello author, thank you very much for your work. When I was running the test, the following error was displayed. What is the 0025. p file mentioned here, and which file did you provide correspond to it? Thank you for your answer!
![image](https://github.com/user-attachments/assets/96bfb7ed-a443-4da4-abf2-d585678fdeec)

**Comment by GuoweiXu368** [comment]
I apologize for the delayed response. This file can be downloaded from the Google Drive [link](https://drive.google.com/drive/folders/1YAa3Lpei0V3-JTEZwSw0WqRfSTYbY-z2) of the pre-trained model.
