### ISSUE TITLE
Problems with training humaneva datasets

### ISSUE THREAD

**Issue by CGYZ515** [GuoweiXu368/SLD-HMP#2]
Hi, thanks for such amazing work, I ran into some problems while training to run main.py with the following command:
`python main.py --cfg humaneva --gpu_index 0`
The error message is as follows
```
Traceback (most recent call last):
  File "main.py", line 431, in <module>
    pose_prior.load_state_dict(model_cp['model_dict'])
  File "/disk/hj/miniconda3/envs/gfenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LinNF:
	Missing key(s) in state_dict: "w1.1.weight", "w1.2.R", "w1.2.bias", "w1.2.Q.U", "w1.3.weight", "w1.4.R", "w1.4.bias", "w1.4.Q.U".
```
Then I checked the corresponding train_nf.py command and found that running python train_nf.py --cfg humaneva --gpu_index 0 would produce something like this：
```
(gfenv) xx@ai204:~/disk/pyproject/SLD-HMP-main$ python train_nf.py --cfg humaneva --gpu_index 0
LinNF(
  (w1): ModuleList(
    (0): LinQR(
      (Q): Orthogonal()
    )
  )
)
>>> total params: 0.00357M
```
It seems that the model structure used by train_nf.py and main.py is different, but I have not modified your code, could you please give me some suggestions? Thank you, best wishes.

**Comment by GuoweiXu368** [comment]
> Hi, thanks for such amazing work, I ran into some problems while training to run main.py with the following command: `python main.py --cfg humaneva --gpu_index 0` The error message is as follows
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 431, in <module>
>     pose_prior.load_state_dict(model_cp['model_dict'])
>   File "/disk/hj/miniconda3/envs/gfenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for LinNF:
> 	Missing key(s) in state_dict: "w1.1.weight", "w1.2.R", "w1.2.bias", "w1.2.Q.U", "w1.3.weight", "w1.4.R", "w1.4.bias", "w1.4.Q.U".
> ```
> 
> Then I checked the corresponding train_nf.py command and found that running python train_nf.py --cfg humaneva --gpu_index 0 would produce something like this：
> 
> ```
> (gfenv) xx@ai204:~/disk/pyproject/SLD-HMP-main$ python train_nf.py --cfg humaneva --gpu_index 0
> LinNF(
>   (w1): ModuleList(
>     (0): LinQR(
>       (Q): Orthogonal()
>     )
>   )
> )
> >>> total params: 0.00357M
> ```
> 
> It seems that the model structure used by train_nf.py and main.py is different, but I have not modified your code, could you please give me some suggestions? Thank you, best wishes.


I'm very sorry for the delayed response; I've been quite busy recently. I'm also puzzled by the issue you've encountered. I set up a new workstation specifically for testing, then cloned the code from GitHub, downloaded the dataset and checkpoints, and ran the exact same commands as you. However, I didn’t encounter the same error.
![image](https://github.com/user-attachments/assets/86cbd62a-0338-452d-af70-3d4fd1711f52)

**Comment by HanZhaang** [comment]
It happened when user re-train a new nf weight. The cause is，in models/motion_pred.py，LinNF.LinNF has different shapes between h36m and h36m_nf:

`        return  model.Model(traj_dim * 3, 128, input_channels = 3,st_gcnn_dropout = cfg.dropout, joints_to_consider = traj_dim, pose_info=pose_info), LinNF.LinNF(data_dim=traj_dim * 3, num_layer=3)`

 `elif model_type == 'h36m_nf' or model_type == 'humaneva_nf':`
        `    print("dataset.traj_dim = {} num_layer = {}".format(dataset.traj_dim, cfg.specs['num_flow_layer']))`
        `    return LinNF.LinNF(data_dim=dataset.traj_dim, num_layer=cfg.specs['num_flow_layer'])`

It works well only if you change：
        `return LinNF.LinNF(data_dim=dataset.traj_dim, num_layer=cfg.specs['num_flow_layer'])`
to
        `return LinNF.LinNF(data_dim=traj_dim * 3, num_layer=3)`
