### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by alanyz106** [GuoweiXu368/SLD-HMP#3]
![image](https://github.com/user-attachments/assets/0ebfb05f-2857-4699-9048-7fec94c22568)
你好，当我加载你给的权重模型时，遇到了上述问题，尝试修改model_cp = pickle.load(open(cp_path, "rb"))为model_cp = torch.load(open(cp_path, "rb"),map_location='cuda:0')，依然不起作用，请问这是什么原因导致的呢

Hello, when I loaded the weight model you provided, I encountered the aforementioned issue. I tried to modify `model_cp = pickle.load(open(cp_path, "rb"))` to `model_cp = torch.load(open(cp_path, "rb"), map_location='cuda:0')`, but it still didn't work. Could you please tell me what might be causing this?

**Comment by GuoweiXu368** [comment]
你好，这是因为我当时是在第7张卡上训练并保存参数的，pickle会把这个信息记录上。我准备更新一下对应的模型参数文件，到时候你再试试。

**Comment by GuoweiXu368** [comment]
你好，我在原始的[链接](https://drive.google.com/drive/folders/1YAa3Lpei0V3-JTEZwSw0WqRfSTYbY-z2?usp=drive_link)中已经上传了新的模型参数文件，命名为0500_cpu.p，这次应该没问题了。

**Comment by alanyz106** [comment]
> 你好，我在原始的[链接](https://drive.google.com/drive/folders/1YAa3Lpei0V3-JTEZwSw0WqRfSTYbY-z2?usp=drive_link)中已经上传了新的模型参数文件，命名为0500_cpu.p，这次应该没问题了。

好的，十分感谢，我已经从头训练了，可以复现

**Comment by GuoweiXu368** [comment]
不客气！非常感谢你对我们工作的关注和认可！
