### ISSUE TITLE
about pose_prior

### ISSUE THREAD

**Issue by alanyz106** [GuoweiXu368/SLD-HMP#4]
请问这个`model, pose_prior = get_model(cfg, dataset, cfg.dataset)`的那个pose_prior起作用吗，我发现模型测试以及训练的时候都没有引用这个prior先验模块，`cp_path = 'results/h36m_nf/models/0025.p' if cfg.dataset == 'h36m' else 'results/humaneva_nf/models/0025.p'`这个0025.p权重我重新训练之后并没有得到，请问这个是怎么得来的呢，十分期待您的答复

**Comment by alanyz106** [comment]
![image](https://github.com/user-attachments/assets/ce3f399f-816d-4ff9-82cb-c7f1e6735cb3)
当我加载其他的先验权重时，会出现以下报错，请问这是什么原因呢？
`188it [00:00, 112278.11it/s]


================================================================================
#1 future: 5/188
#<10 future: 120/188
Human pose information:  {'keep_joints': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), 'parents': [-1, 0, 1, 2, 3, 1, 5, 6, 0, 8, 9, 0, 11, 12, 1], 'joints_left': [2, 3, 4, 8, 9, 10], 'joints_right': [5, 6, 7, 11, 12, 13]}
loading model from checkpoint: results/humaneva_nf/models/0500.p
Traceback (most recent call last):
  File "main.py", line 431, in <module>
    pose_prior.load_state_dict(model_cp['model_dict'])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1918, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LinNF:
        Missing key(s) in state_dict: "w1.1.weight", "w1.2.R", "w1.2.bias", "w1.2.Q.U", "w1.3.weight", "w1.4.R", "w1.4.bias", "w1.4.Q.U". `

**Comment by alanyz106** [comment]
我知道了，`LinNF.LinNF(data_dim=traj_dim * 3, num_layer=3)`要改成num_layer为1，并且和之前加载0025p权重结果是一样的，请问这个num_layer有什么影响吗

**Comment by GuoweiXu368** [comment]
这个pose prior的作用是约束生成的结果是正常的pose，对结果的影响可以看我的补充材料的Table 5。之前很多方法都采用了，比如GSPS，STARS。我之前为了公平比较，好像没有对pose prior进行改动，直接用了之前方法的pose prior的参数。因此你说的num_layer我也不确定具体的影响是什么，你可以做一下实验分析一下。

**Comment by alanyz106** [comment]
好的，十分感谢您的回复
